package com.bulain.hibernate.entity;
// Generated 2011-10-22 0:00:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * GroupPermission generated by hbm2java
 */
public class GroupPermission implements java.io.Serializable {
    private static final long serialVersionUID = -2349734642923059718L;

    private Integer id;
    private Group groups;
    private String permission;
    private String createdBy;
    private Date createdAt;
    private String updatedBy;
    private Date updatedAt;

    public GroupPermission() {
    }

    public GroupPermission(Group groups, String permission, String createdBy, Date createdAt, String updatedBy,
            Date updatedAt) {
        this.groups = groups;
        this.permission = permission;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Group getGroups() {
        return this.groups;
    }

    public void setGroups(Group groups) {
        this.groups = groups;
    }
    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
