package com.bulain.hibernate.entity;
// Generated 2011-10-22 0:00:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * GroupUser generated by hbm2java
 */
public class GroupUser implements java.io.Serializable {
    private static final long serialVersionUID = 3571331817553138992L;

    private Integer id;
    private Group groups;
    private Integer userId;
    private String createdBy;
    private Date createdAt;
    private String updatedBy;
    private Date updatedAt;

    public GroupUser() {
    }

    public GroupUser(Group groups, Integer userId, String createdBy, Date createdAt, String updatedBy, Date updatedAt) {
        this.groups = groups;
        this.userId = userId;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Group getGroups() {
        return this.groups;
    }

    public void setGroups(Group groups) {
        this.groups = groups;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
